config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'high_voltage/pages#show', id: 'landing'
  resources :arrangements, only: [:index, :show]
  get 'contact' => 'high_voltage/pages#show', id: 'contact'
  get 'flowers' => 'arrangements#index'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/arrangement.rb
class Arrangement < ActiveRecord::Base
  has_many :arrangement_flowers
  has_many :flowers, through: :arrangement_flowers

  validates :availability, inclusion: {in: %w(available not_available)}
  validates :visibility, inclusion: {in: %w(visible not_visible)}
  validates :container_type, inclusion: {in: %w(vase box)}
  validates :name, :item_number, :price, :availability, :width, :height, :description, :visibility, :container_type, presence: true
  accepts_nested_attributes_for :arrangement_flowers, allow_destroy: true

  has_attached_file :image, styles: {medium: ["100x100>", :jpg]}
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/gif", "image/png"]

  def available?
    availability == 'available'
  end

  def visible?
    visibility == 'visible'
  end
end

app/models/arrangement_flower.rb
class ArrangementFlower < ActiveRecord::Base
  belongs_to :flower
  belongs_to :arrangement

  accepts_nested_attributes_for :flower, allow_destroy: true

end

app/models/flower.rb
class Flower < ActiveRecord::Base
  has_many :arrangement_flowers
  has_many :arrangements, through: :arrangement_flowers

  validates :flower_type, presence: true, uniqueness: true


  def name
  	flower_type
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/arrangements_controller.rb
class ArrangementsController < ApplicationController
	def index 
		@arrangements = Arrangement.all 
	end

	def show
    @arrangements = Arrangement.find(params[:id])
  end

  private

  def arrangement_params
    params.require(:arrangement).permit(:name, :item_number, :price, :availability, :width, :height, :description, :visibility, :container_type, :image, :flower_ids)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arrangements_helper.rb
module ArrangementsHelper
end

app/views/arrangements/index.html.slim
#main
  #top
    h2 Flowers
  #middle
    .gallery
      - @arrangements.each do |arrangement|
        #item
          - if arrangement.image?
              = link_to image_tag(arrangement.image.url, class:'item-image', alt: arrangement.name), arrangement_path(arrangement)

          - else
              img src="http://placehold.it/400x400"

          h4.caption = link_to arrangement.name.upcase, arrangement_path(arrangement)
          h5.details = number_to_currency(arrangement.price, unit: "KWD ", precision: 3)
          h5.details = arrangement.description

app/views/layouts/application.html.slim
doctype html
html
  head
    title Fleur Flowers & Gifts
    meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"
    = stylesheet_link_tag "application"
    = javascript_include_tag "https://maps.googleapis.com/maps/api/js"
    = javascript_include_tag "application"
  body
    header.main-header
      =link_to '/', class: "site-logo"
        img src= '/assets/fleur_logo_transparent'

      ul.nav
        li: a href= "/flowers" FLOWER SHOP
        / li: a href= "#" GIFTS
        li: a href= "#" BAKERY
        li: a href= "#" EVENTS
        li: a href= "/contact" CONTACT

    == yield

  footer
    p#copyright &copy; #{Date.today.year} Fleur Flowers & Gifts

app/views/pages/contact.html.slim
h2 Our Locations & Contact Information

#map_1
#map_2

.location
  h3.address Fleur Flower's & Gifts
  h4.address Yarmouk
  h4.address Block 2 Street 2
  h4.address 99638855 | 25329414


.location
  h3.address Fleur's Corner
  h4.address Khaldiya
  h4.address Block 2 Al Orouba Street
  h4.address 97118668 | 24825970

app/views/pages/landing.html.slim
#hero-image
  .hero-header
     h1 Everything special
#main
  #middle
    h2.heading =link_to('Follow us on Instagram @fleurkw', 'https://instagram.com/fleurkw/', target: "_blank")
    .instagallery
       - Instagram.user_recent_media("24689190", {count: 4}).each do |pic|
         figure.instaitem
          = link_to image_tag(pic.images.standard_resolution.url, class: 'insta-image', alt: pic.caption.text), pic.link
          figcaption
            = link_to pic.caption.text, pic.link, target: "_blank"